services:
  agents:
    build:
        context: .
    environment:
      - MCP_SERVER_URL=http://mcp-gateway:8811/sse
    restart: no
    depends_on:
      - mcp-gateway
    models:
      agent:
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL

  mcp-gateway:
    # mcp-gateway secures your MCP servers
    image: docker/mcp-gateway:latest
    use_api_socket: true
    command:
      - --transport=sse
      # add any MCP servers you want to use
      - --servers=duckduckgo
      - --tools=search,fetch_content

models:
  agent:
    model: ai/qwen3
    context_size: 8192
    runtime_flags:
      - --no-prefill-assistant
